"""Webhook error responses carry registered machine-readable codes (#569).

The webhook routes used to raise bare ``HTTPException``s whose only identity
was a human-readable ``detail`` string, while the rest of the API speaks in
registered error codes (docs/ERROR_CODES.md). Every webhook 4xx now raises
``WebhookHTTPException`` — a ``StarletteHTTPException`` carrying an
``error_code`` attribute — and the RFC 7807 handler surfaces it as an
``error_code`` extension member on the problem response. The ``detail`` text
is unchanged, so existing consumers keep working.
"""

from __future__ import annotations

from typing import Any

from starlette.exceptions import HTTPException as StarletteHTTPException

# Codes registered in docs/ERROR_CODES.md (Webhook Error Codes section) and
# enforced by scripts/lint_error_codes.py. 4xx only: 5xx responses are
# generated by the service layer / generic handlers.
WEBHOOK_NOT_FOUND = "webhook_not_found"
DELIVERY_NOT_FOUND = "delivery_not_found"
WEBHOOK_CONFLICT = "conflict"
VALIDATION_ERROR = "validation_error"

# Issue #569: specific codes so clients can branch on *why* a request failed
# instead of parsing detail strings. All registered in docs/ERROR_CODES.md.
INVALID_WEBHOOK_URL = "invalid_webhook_url"
WEBHOOK_DELETED_CONFLICT = "webhook_deleted_conflict"
WEBHOOK_LIMIT_REACHED = "webhook_limit_reached"
DELIVERY_NOT_RETRYABLE = "delivery_not_retryable"
DELIVERY_IN_PROGRESS = "delivery_in_progress"
DELIVERY_NOT_REPLAYABLE = "delivery_not_replayable"


class WebhookHTTPException(StarletteHTTPException):
    """An HTTPException that carries a registered error code (#569)."""

    def __init__(
        self,
        *,
        status_code: int,
        detail: Any,
        error_code: str,
        headers: dict[str, str] | None = None,
    ) -> None:
        super().__init__(status_code=status_code, detail=detail, headers=headers)
        self.error_code = error_code
