"""Webhook error responses carry registered machine-readable codes (#569).

The webhook routes used to raise bare ``HTTPException``s whose only identity
was a human-readable ``detail`` string, while the rest of the API speaks in
registered error codes (docs/ERROR_CODES.md). Every webhook 4xx now raises
``WebhookHTTPException`` — a ``StarletteHTTPException`` carrying an
``error_code`` attribute — and the RFC 7807 handler surfaces it as an
``error_code`` extension member on the problem response. The ``detail`` text
is unchanged, so existing consumers keep working.
"""

from __future__ import annotations

from typing import Any

from app.api.coded_errors import CodedHTTPException

# Codes registered in docs/ERROR_CODES.md (Webhook Error Codes section) and
# enforced by scripts/lint_error_codes.py. 4xx only: 5xx responses are
# generated by the service layer / generic handlers.
WEBHOOK_NOT_FOUND = "webhook_not_found"
DELIVERY_NOT_FOUND = "delivery_not_found"
WEBHOOK_CONFLICT = "conflict"
VALIDATION_ERROR = "validation_error"


class WebhookHTTPException(CodedHTTPException):
    """An HTTPException that carries a registered error code (#569)."""

    def __init__(
        self,
        *,
        status_code: int,
        detail: Any,
        error_code: str | None = None,
        headers: dict[str, str] | None = None,
    ) -> None:
        # CodedHTTPException supplies the registered generic code for the
        # status when ``error_code`` is omitted; webhook call-sites always pass
        # their domain code explicitly.
        super().__init__(status_code=status_code, detail=detail, headers=headers, error_code=error_code)
